const CONFIG = {
    introTitle: 'Chào Phươnggggggg!',
    introDesc: `Mặc dù đã nhiều lần cố gắng bắt chuyện với em nhưng anh đều thất bại :< `,
    btnIntro: 'Vậy sao',
    title: 'Mình có thể làm bạn chứ  😙',
    desc: 'Điiiiiiiiiii màaaa :<  ',
    btnYes: 'Được thuiiii ',
    btnNo: ' không 😢😢,
    question:'Trên thế giới hơn 7 tỉ người mà sao anh chỉ muốn bên cạnh em :< ',
    btnReply: 'Em biết không ? ',
    reply: ' Em muốn làm bạn với anh <33 ',
    mess: 'Anh biết mà 🥰. Yêu em nhiều nhiều 😘😘',
    messDesc: 'Anh có thể nói chuyện với em không :< .',
    btnAccept: 'Okiiiii lun <3',
    messLink: 'http://fb.com' https://www.facebook.com/Minhunt131
